### ISSUE TITLE
Dependency issues running ClamAV v102

### ISSUE THREAD

**Issue by sethsacher** [kindlyops/lambda-clamav-layer#3]
The most recent tagged release includes ClamAV v101, which is incompatible with the latest virus definition files picked up by freshclam. I ran the build script and created a new layer with the resulting ClamAV v102 package , but I'm running into a series of dependency issues (libprelude, libcurl, and libssh2 are a few of them). Requesting an updated version of the script to build a valid ClamAV v102 package.

**Comment by statik** [comment]
@sethsacher thanks for the report! Which lambda runtime are you seeing the dependency issues with? I know of folks using it previously with python and node runtimes, just want to make sure we look at the right one.

**Comment by sethsacher** [comment]
Node 12. I just submitted https://github.com/kindlyops/lambda-clamav-layer/pull/4 which is working right now for me!

**Comment by statik** [comment]
Thanks @sethsacher! Published v0.5 with your fixes.
