### ISSUE TITLE
centos rpm is a dead link

### ISSUE THREAD

**Issue by rileypriddle** [kindlyops/lambda-clamav-layer#7]
http://mirror.centos.org/centos/7/os/x86_64/Packages/glibc-2.17-307.el7.1.x86_64.rpm is dead

i replaced it with https://linuxsoft.cern.ch/cern/centos/7/updates/x86_64/Packages/Packages/glibc-2.17-307.el7.1.x86_64.rpm

suggesting local rpm files being added through docker build as a replacement to the curls

**Comment by statik** [comment]
Thanks for reporting this! I agree that refactoring to be less fragile is a good idea.

#8 should fix things for the moment.
